### ISSUE TITLE
请问一下大佬，ncnn的模型文件时由两个，你这里只有一个？

### ISSUE THREAD

**Issue by wuxiaolianggit** [caishanli/pyncnn#1]
请问一下大佬，ncnn的模型文件时由两个，你这里只有一个param，您这里param和c++版本param是一样的吗？还是把c++版param和bin文件合在一起了呢 @caishanli

**Comment by caishanli** [comment]
接口还是和ncnn的一致的，只是测试工程没有放.bin文件所以没加载

**Comment by wuxiaolianggit** [comment]
@多谢大佬回复啊
