### ISSUE TITLE
Support for the latest NCNN

### ISSUE THREAD

**Issue by rose-jinyang** [caishanli/pyncnn#11]
Hello
How are you?
Thanks for contributing this project.
I am going to use this python binding for NCNN.
I set all the parameters and configured with cmake exactly.
While building I met the following issue.

![image](https://user-images.githubusercontent.com/47862419/99644044-67c7d380-2a88-11eb-9a4e-4822ad962f82.png)

Could u help me to solve this issue?
Thanks

**Comment by caishanli** [comment]
hi, code has updated with latest ncnn.

**Comment by rose-jinyang** [comment]
Thanks for your quick reply.

**Comment by rose-jinyang** [comment]
Hello
Did u check the installation?
First, there are your customized paths in the CMakeLists.txt.

![image](https://user-images.githubusercontent.com/47862419/99824415-a779e280-2b90-11eb-94ac-17ee3dc9fa60.png)


I changed the paths.
Secondly, I met the following issue when configure with cmake.

![image](https://user-images.githubusercontent.com/47862419/99824245-6da8dc00-2b90-11eb-89a3-bb0b6b08250a.png)

So I commented the command `find_package(Python3)` in `CMakeLists.txt` and the above issue was disappeared.

Lastly, when building with make command, I met the following issue again.

![image](https://user-images.githubusercontent.com/47862419/99826667-a4342600-2b93-11eb-8e41-229b6ca1679c.png)


Please let me know the solution.
Thanks
