### ISSUE TITLE
Issues on installing

### ISSUE THREAD

**Issue by rose-jinyang** [caishanli/pyncnn#12]
Hello
Did u check the installation?
First, there are your customized paths in the CMakeLists.txt.

![image](https://user-images.githubusercontent.com/47862419/99824415-a779e280-2b90-11eb-94ac-17ee3dc9fa60.png)

I changed the paths.
Secondly, I met the following issue when configure with cmake.

![image](https://user-images.githubusercontent.com/47862419/99824245-6da8dc00-2b90-11eb-89a3-bb0b6b08250a.png)

So I commented the command `find_package(Python3)` in `CMakeLists.txt` and the above issue was disappeared.

Lastly, when building with make command, I met the following issue again.

![image](https://user-images.githubusercontent.com/47862419/99826667-a4342600-2b93-11eb-8e41-229b6ca1679c.png)

Please let me know the solution.
Thanks

**Comment by caishanli** [comment]
Hello, customized paths should be removed.
And what's your cmake version?

**Comment by rose-jinyang** [comment]
CMake version: 3.16.3
Python 3.8.6
NCNN-20200916

**Comment by caishanli** [comment]
I fixed these problems and test on msvc2019 and ubuntu18.04. You can update and try.

**Comment by rose-jinyang** [comment]
Hello
There is the same issue when compiling main.cpp.

![image](https://user-images.githubusercontent.com/47862419/99868783-949ef680-2c00-11eb-873c-3ef85f41bebc.png)

Please check.
My OS: Ubuntu 20.10
gcc: 10.2.0

The configuration result by cmake is the following.

![image](https://user-images.githubusercontent.com/47862419/99868901-c5336000-2c01-11eb-8c14-73bc2a02225d.png)

**Comment by caishanli** [comment]
Is your pyncnn code updated？
main.cpp:531 should be
`.def("extract", (int (Extractor::*)(const char *, Mat &, int)) & Extractor::extract,`

**Comment by rose-jinyang** [comment]
Yes, Please check

![image](https://user-images.githubusercontent.com/47862419/99872010-94f7bb80-2c19-11eb-8268-cbb48c66c371.png)

**Comment by caishanli** [comment]
Yesterday I update this code with ncnn master and add third param int to this function, so you can build with ncnn master without modify the code.
If you want to build with NCNN-20200916 release, please modify main.cpp:531-532 as follow:
`.def("extract", (int (Extractor::*)(const char *, Mat &)) & Extractor::extract, `
`    "get result by blob name", py::arg("blob_name"), py::arg("feat"))`
and the same as main.cpp:535-536, and now you should build success.

**Comment by rose-jinyang** [comment]
Thanks
The compile issue was disappeared.
But When I test the script "tests/test.py", I met the following issue.

![image](https://user-images.githubusercontent.com/47862419/99878583-84f3d200-2c41-11eb-81de-db0334755067.png)

Could u fix this issue asap?
Thanks

**Comment by rose-jinyang** [comment]
The issue has been disappeared.
Thanks.

**Comment by caishanli** [comment]
You are welcome.
