### ISSUE TITLE
where to place the pybind11 folder

### ISSUE THREAD

**Issue by xidianzhuxi** [caishanli/pyncnn#15]
i know nothing about cmake , i have success make ncnn and pybind11 .but just cmake the pyncnn always said: 

`CMake Error at CMakeLists.txt:13 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.
`
what is the problem? and how to change the cmake file

**Comment by xidianzhuxi** [comment]
oh my god !when i cmake success. the src dir is just empty! whereis the main.cpp?
![image](https://user-images.githubusercontent.com/40211659/102633159-02502b00-418b-11eb-9907-bb7ce85abdd4.png)

**Comment by caishanli** [comment]
pyncnn have merged to [Tencent/ncnn](https://github.com/Tencent/ncnn/tree/master/python), and will auto place pybind11 in ncnn/python/pybind11 when you init git submodules.
