### ISSUE TITLE
make报错

### ISSUE THREAD

**Issue by lawo123** [caishanli/pyncnn#2]
前边编译都没问题，进行到make那一步的时候报这种错是怎么回事呢？
![image](https://user-images.githubusercontent.com/44777088/75652490-22fbd280-5c96-11ea-971f-8c3d0d56f6df.png)

**Comment by lawo123** [comment]
@caishanli

**Comment by caishanli** [comment]
> 前边编译都没问题，进行到make那一步的时候报这种错是怎么回事呢？
> ![image](https://user-images.githubusercontent.com/44777088/75652490-22fbd280-5c96-11ea-971f-8c3d0d56f6df.png)
已经改好了。update一下
