### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by huoshuai0531** [caishanli/pyncnn#6]
编译完成后 在./pyncnn/python路径下 import ncnn没有报错，但是，换个路径出现ModuleNotFoundError，这个问题的原因大概是什么？

**Comment by suay1113** [comment]
把编译后的pyncnn/python/ncnn.egg-info/和pyncnn/python/ncnn/文件夹拷贝到python的dist-packages中

for me
`
cp -r pyncnn/python/ncnn.egg-info/ /usr/local/lib/python3.6/dist-packages   
`
`
cp -r pyncnn/python/ncnn/ /usr/local/lib/python3.6/dist-packages
`
