### ISSUE TITLE
cmake 出错

### ISSUE THREAD

**Issue by rainfly123** [caishanli/pyncnn#8]
在build目录执行cmake -DCMAKE_PREFIX_PATH=/home/pi/ncnn/ncnn/build/install/lib/cmake/ncnn/ ..
出错：
CMake Error at /usr/share/cmake-3.13/Modules/FindPython/Support.cmake:1236 (add_library):
  No SOURCES given to target: pyncnn
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPython3.cmake:167 (__Python3_add_library)
  /usr/local/share/cmake/pybind11/pybind11NewTools.cmake:138 (python3_add_library)
  CMakeLists.txt:24 (pybind11_add_module)

**Comment by rainfly123** [comment]
find_package (Python3 COMPONENTS Interpreter Development)
去除这一行 就可以啦

**Comment by caishanli** [comment]
有可能是cmake的版本不同造成的。我测试的是cmake3.15
